// ignore_for_file: constant_identifier_names
/* 

  Flutter icons BellugaIcons
  Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
  This font was generated by FlutterIcon.com, which is derived from Fontello.

  To use this font, place it in your fonts/ directory and include the following in your pubspec.yaml

  flutter:
  fonts:
    - family:  BellugaIcons
      fonts:
        - asset: fonts/BellugaIcons.ttf

  * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
    Author:    Dave Gandy
    License:   SIL ()
    Homepage:  http://fortawesome.github.com/Font-Awesome/

*/

import 'package:flutter/widgets.dart';

class BellugaIcons {
  BellugaIcons._();

  static const _kFontFam = 'BellugaIcons';
  static const String? _kFontPkg = null;

  static const IconData sticky_note = IconData(0xf249, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sticky_note_outline = IconData(0xf24a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
